### ISSUE TITLE
请教下这种如何在Unraid下搭建？

### ISSUE THREAD

**Issue by tyhunter** [ihainan/JableTVDownload-WebUI#2]
貌似没有发布到仓库，只能本地build

**Comment by ihainan** [comment]
@tyhunter 我近期会尝试发布到仓库，稍等我几天哈。

**Comment by ihainan** [comment]
@tyhunter 可以试一下如下 docker-compose file：

```
services:
  jable-downloader-service:
    container_name: jable-downloader-service
    image: bypass42/jable-downloader-service:latest
    volumes:
      - /home/ihainan/test/downloads:/app/downloads
      - /home/ihainan/test/db:/app/db

  jable-downloader-ui:
    container_name: jable-downloader-ui
    image: bypass42/jable-downloader-ui:latest
    environment:
      - API_ENDPOINT="http://jable-downloader-service:3000"
    ports:
      - 41056:80
    depends_on:
      - jable-downloader-service
```
