### ISSUE TITLE
 docker-compose up -d --build 不过

### ISSUE THREAD

**Issue by xinmans** [ihainan/JableTVDownload-WebUI#4]
=> ERROR [jable-downloader-service 23/24] RUN cd server && npm install                                                  25.1s
------
 > [jable-downloader-service 23/24] RUN cd server && npm install:
12.44 npm WARN deprecated are-we-there-yet@3.0.1: This package is no longer supported.
12.57 npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
12.73 npm WARN deprecated gauge@4.0.4: This package is no longer supported.
12.86 npm WARN deprecated npmlog@6.0.2: This package is no longer supported.
12.93 npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
13.12 npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
13.23 npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
24.96 npm ERR! code 1
24.96 npm ERR! path /app/server/node_modules/better-sqlite3
24.96 npm ERR! command failed
24.96 npm ERR! command sh -c prebuild-install || node-gyp rebuild --release
24.97 npm ERR! prebuild-install warn install Error relocating /app/server/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE15_M_replace_coldEPcmPKcmm: symbol not found
24.97 npm ERR! gyp info it worked if it ends with ok
24.97 npm ERR! gyp info using node-gyp@8.4.1

**Comment by ihainan** [comment]
@xinmans xinmans可以试试使用 build 好的版本，我还在测试，等稳定了会合并回主分支：

``` yaml
services:
  jable-downloader-service:
    container_name: jable-downloader-service
    image: bypass42/jable-downloader-service:latest
    volumes:
      - /home/ihainan/test/downloads:/app/downloads
      - /home/ihainan/test/db:/app/db

  jable-downloader-ui:
    container_name: jable-downloader-ui
    image: bypass42/jable-downloader-ui:latest
    environment:
      - API_ENDPOINT="http://jable-downloader-service:3000"
    ports:
      - 41056:80
    depends_on:
      - jable-downloader-service
```
